"""user_by_id migration

Revision ID: 619ea43cd522
Revises: a5d31ce9c61b
Create Date: 2024-10-11 12:52:19.321479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619ea43cd522'
down_revision = 'a5d31ce9c61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
